[package]
name = "rtsp_to"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.17"
gstreamer = "0.18"
gstreamer-base = "0.18"
gstreamer-video = "0.18"
